package com.aivideotranscriber.util

data class LanguageOption(val code: String, val displayName: String)

/**
 * The ~99 languages Whisper was trained on (from OpenAI's published language table), plus
 * "auto" for automatic detection. Passed straight through to whisper.cpp's `language` param.
 */
object LanguageOptions {
    val AUTO = LanguageOption("auto", "Auto Detect")

    val ALL: List<LanguageOption> = listOf(
        AUTO,
        LanguageOption("en", "English"),
        LanguageOption("zh", "Chinese"),
        LanguageOption("de", "German"),
        LanguageOption("es", "Spanish"),
        LanguageOption("ru", "Russian"),
        LanguageOption("ko", "Korean"),
        LanguageOption("fr", "French"),
        LanguageOption("ja", "Japanese"),
        LanguageOption("pt", "Portuguese"),
        LanguageOption("tr", "Turkish"),
        LanguageOption("pl", "Polish"),
        LanguageOption("ca", "Catalan"),
        LanguageOption("nl", "Dutch"),
        LanguageOption("ar", "Arabic"),
        LanguageOption("sv", "Swedish"),
        LanguageOption("it", "Italian"),
        LanguageOption("id", "Indonesian"),
        LanguageOption("hi", "Hindi"),
        LanguageOption("fi", "Finnish"),
        LanguageOption("vi", "Vietnamese"),
        LanguageOption("he", "Hebrew"),
        LanguageOption("uk", "Ukrainian"),
        LanguageOption("el", "Greek"),
        LanguageOption("ms", "Malay"),
        LanguageOption("cs", "Czech"),
        LanguageOption("ro", "Romanian"),
        LanguageOption("da", "Danish"),
        LanguageOption("hu", "Hungarian"),
        LanguageOption("ta", "Tamil"),
        LanguageOption("no", "Norwegian"),
        LanguageOption("th", "Thai"),
        LanguageOption("ur", "Urdu"),
        LanguageOption("hr", "Croatian"),
        LanguageOption("bg", "Bulgarian"),
        LanguageOption("lt", "Lithuanian"),
        LanguageOption("la", "Latin"),
        LanguageOption("mi", "Maori"),
        LanguageOption("ml", "Malayalam"),
        LanguageOption("cy", "Welsh"),
        LanguageOption("sk", "Slovak"),
        LanguageOption("te", "Telugu"),
        LanguageOption("fa", "Persian"),
        LanguageOption("lv", "Latvian"),
        LanguageOption("bn", "Bengali"),
        LanguageOption("sr", "Serbian"),
        LanguageOption("az", "Azerbaijani"),
        LanguageOption("sl", "Slovenian"),
        LanguageOption("kn", "Kannada"),
        LanguageOption("et", "Estonian"),
        LanguageOption("mk", "Macedonian"),
        LanguageOption("br", "Breton"),
        LanguageOption("eu", "Basque"),
        LanguageOption("is", "Icelandic"),
        LanguageOption("hy", "Armenian"),
        LanguageOption("ne", "Nepali"),
        LanguageOption("mn", "Mongolian"),
        LanguageOption("bs", "Bosnian"),
        LanguageOption("kk", "Kazakh"),
        LanguageOption("sq", "Albanian"),
        LanguageOption("sw", "Swahili"),
        LanguageOption("gl", "Galician"),
        LanguageOption("mr", "Marathi"),
        LanguageOption("pa", "Punjabi"),
        LanguageOption("si", "Sinhala"),
        LanguageOption("km", "Khmer"),
        LanguageOption("sn", "Shona"),
        LanguageOption("yo", "Yoruba"),
        LanguageOption("so", "Somali"),
        LanguageOption("af", "Afrikaans"),
        LanguageOption("oc", "Occitan"),
        LanguageOption("ka", "Georgian"),
        LanguageOption("be", "Belarusian"),
        LanguageOption("tg", "Tajik"),
        LanguageOption("sd", "Sindhi"),
        LanguageOption("gu", "Gujarati"),
        LanguageOption("am", "Amharic"),
        LanguageOption("yi", "Yiddish"),
        LanguageOption("lo", "Lao"),
        LanguageOption("uz", "Uzbek"),
        LanguageOption("fo", "Faroese"),
        LanguageOption("ht", "Haitian Creole"),
        LanguageOption("ps", "Pashto"),
        LanguageOption("tk", "Turkmen"),
        LanguageOption("nn", "Norwegian Nynorsk"),
        LanguageOption("mt", "Maltese"),
        LanguageOption("sa", "Sanskrit"),
        LanguageOption("lb", "Luxembourgish"),
        LanguageOption("my", "Myanmar"),
        LanguageOption("bo", "Tibetan"),
        LanguageOption("tl", "Tagalog"),
        LanguageOption("mg", "Malagasy"),
        LanguageOption("as", "Assamese"),
        LanguageOption("tt", "Tatar"),
        LanguageOption("haw", "Hawaiian"),
        LanguageOption("ln", "Lingala"),
        LanguageOption("ha", "Hausa"),
        LanguageOption("ba", "Bashkir"),
        LanguageOption("jw", "Javanese"),
        LanguageOption("su", "Sundanese"),
        LanguageOption("yue", "Cantonese"),
    )
}
